Repository Unifacs-Portfolio/fast-reserv, pull requests merged in 2025-05, with the labels that each got.

#1 Criação de estrutura de pastas
  .gitignore
  .npmrc
  LICENSE
  backend/README.md
  backend/src/Datenbank/configdb.ts
  backend/src/app.ts
  backend/src/env.ts
  backend/src/server.ts
  backend/vitest.config.ts
  biome.json
  frontend/README.md
  frontend/public/assets/css/styles.css
  frontend/public/assets/images/cafezinhobanner.gif
  frontend/public/assets/images/faviconcoffe.jpg
  frontend/public/assets/images/paozinho1.jpg
  frontend/public/assets/images/paozinho2.jpg
  frontend/public/assets/js/main.js
  frontend/public/assets/js/reportApi.js
  frontend/public/assets/js/reservationApi.js
  frontend/public/attendent.html
  frontend/public/index.html
  frontend/public/manager.html
  frontend/public/waiter.html
  package-lock.json
  package.json
  tsconfig.json
Labels: enhancement

#6 feat: Adicionado o Biome no projeto
  backend/src/server.ts
  biome.json
  package-lock.json
  package.json
  tsconfig.json
Labels: enhancement

#7 feat: Adicionado o DotEnv
  .env.example
  .gitignore
  backend/src/Datenbank/configdb.ts
  backend/src/app.ts
  backend/src/env.ts
  backend/src/server.ts
  package-lock.json
  package.json
Labels: enhancement

#14 feat(reserva): adicionar entidade Reserva e repositório SQLite
  backend/src/entities/Reserva.ts
  backend/src/repositories/ReservaRepository.ts
  backend/src/repositories/sqlite/SqliteReservaRepository.ts
Labels: enhancement

#12 Feature para router de atendente
  backend/src/app.ts
  backend/src/http/controllers/atendente/atendente.route.ts
Labels: enhancement

#13 feat(atendente): criar estrutura inicial do CriarReservaController
  backend/src/BasisData/database.db
  backend/src/Datenbank/configdb.ts
  backend/src/entities/Reserva.ts
  backend/src/http/controllers/atendente/CriarReservaController.ts
  backend/src/http/controllers/atendente/atendente.route.ts
  backend/src/repositories/ReservaRepository.ts
  backend/src/repositories/sqlite/SqliteReservaRepository.ts
  backend/src/useCases/CriarReservaUseCase.ts
Labels: enhancement

#18 Bugfix/validation-date
  backend/src/BasisData/database.db
  backend/src/app.ts
  backend/src/entities/Reserva.ts
  backend/src/http/controllers/atendente/CriarReservaController.ts
  backend/src/useCases/CriarReservaUseCase.ts
Labels: bug

#21 test: ajusta configuração do Vitest e dependências
  .gitignore
  .vscode/settings.json
  package-lock.json
  package.json
  vitest.config.ts
  vitest.units.ts
Labels: enhancement

#19 Feature/deletar-reservas
  backend/src/BasisData/database.db
  backend/src/http/controllers/atendente/DeletarReservaController.ts
  backend/src/http/controllers/atendente/atendente.route.ts
  backend/src/repositories/ReservaRepository.ts
  backend/src/repositories/sqlite/SqliteReservaRepository.ts
  backend/src/useCases/DeletarReservaUseCase.ts
  backend/src/useCases/factories/makeDeletarReservaUseCase.ts
  frontend/public/assets/css/styles.css
  frontend/public/assets/images/paozinho1.jpg
  frontend/public/assets/images/paozinho2.jpg
  frontend/public/index.html
Labels: enhancement

#20 Potential fix for code scanning alert no. 1: Workflow does not contain permissions
  .github/workflows/always-pass.yml
Labels: bug

#24 test: implementa repositório em memória e teste de caso de uso para deletar reservas
  backend/src/repositories/inMemory/InMemoryReservaRepository.ts
  backend/src/useCases/DeletarReservaUseCase.test.ts
Labels: feature

#25 Feature/express-for-frontend
  backend/src/app.ts
  package.json
Labels: feature

#27 test(ConfirmarReserva)): adiciona testes para confirmar reservas no caso de uso
  backend/src/repositories/ReservaRepository.ts
  backend/src/repositories/inMemory/InMemoryReservaRepository.ts
  backend/src/useCases/ConfirmarReservaUseCase.test.ts
Labels: feature

#28 test(e2e): adiciona testes ent-to-end para criação e cancelamento de reservas
  .env.example
  .github/workflows/run-e2e-tests.yml
  .gitignore
  backend/src/env.ts
  backend/src/http/controllers/atendente/CancelarReservaController.test.ts
  backend/src/http/controllers/atendente/CriarReservaController.test.ts
  backend/src/utils/checkRouteExists.ts
  backend/src/utils/generateDatabasePath.ts
  package-lock.json
  package.json
  vitest.e2e.ts
Labels: feature
